###############################################################################
#                              🏆 Mo'Bosses 🏆                               #
#         Продвинутая система боссов для Minecraft Spigot 1.21+              #
#                   ⚔️ Без имбы, с балансом и прогрессией! ⚔️                #
###############################################################################

name: MoBosses
version: "1.11.1"
main: ru.mobosses.PluginUnit
api-version: "1.21"

# ---------------------------------------------------------------------------
#  📋 Метаданные плагина
# ---------------------------------------------------------------------------
author: MairwunNx
website: "https://github.com/MairwunNx/MoBosses"
description: |
  🎮✨ Mo'Bosses - продвинутый плагин для Minecraft Spigot! ✨🎮
  
  🔥 ОСНОВНЫЕ ВОЗМОЖНОСТИ:
  ├─ 🎯 Сбалансированная система боссов без имбы
  ├─ 📈 Прогрессия игрока через убийства боссов  
  ├─ 💎 Качественный лут с разумными наградами
  ├─ ✨ Красивые визуальные и звуковые эффекты
  ├─ ⚙️ Гибкая система конфигурации
  ├─ 🏆 Система уведомлений и достижений
  └─ 🛡️ Антиимба валидация и тестирование
  
  🎲 КЛАССЫ БОССОВ: Common → Uncommon → Rare → Epic → Legendary → Mythic
  🗡️ Улучшенная альтернатива InfernalMobs с современным подходом!
  
  💪 Каждый босс масштабируется по здоровью, урону и способностям.
  🎁 Уникальные таблицы лута для каждого уровня сложности.
  🎨 Полная настройка через YAML конфигурацию.

# ---------------------------------------------------------------------------
#  🔗 Зависимости
# ---------------------------------------------------------------------------
softdepend:
  - WorldGuard    # Поддержка регионов и защищённых зон

# ---------------------------------------------------------------------------
#  ⌨️ Команды плагина
# ---------------------------------------------------------------------------
commands:
  mobosses:
    description: "🎮 Главная команда плагина Mo'Bosses для управления боссами"
    usage: "/<command> [reload|spawn <сущность> <уровень> <класс>|killall]"
    permission: mobosses.admin
    aliases: [ mb, moboss ]

# ---------------------------------------------------------------------------
#  🔐 Система разрешений
# ---------------------------------------------------------------------------
permissions:
  # Административные разрешения
  mobosses.admin:
    description: "👑 Полный доступ ко всем административным командам Mo'Bosses"
    default: op
    children:
      mobosses.reload: true
      mobosses.spawn: true
      mobosses.killall: true
      mobosses.debug: true

  # Перезагрузка конфигурации
  mobosses.reload:
    description: "🔄 Разрешает перезагружать конфигурацию и языковые файлы"
    default: op

  # Спавн боссов
  mobosses.spawn:
    description: "✨ Разрешает создавать боссов с настраиваемыми параметрами"
    default: op

  # Удаление всех боссов
  mobosses.killall:
    description: "💀 Разрешает убивать всех активных боссов на сервере"
    default: op

  # Режим отладки
  mobosses.debug:
    description: "🐛 Разрешает включать режим отладки и просматривать debug информацию"
    default: op
